config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'articles#blog'

  get 'blog',          to: 'articles#blog'
  get 'basics',        to: 'articles#basics'
  get 'guides',        to: 'articles#guides'
  get '/articles/:id', to: 'articles#show', as: 'article'

  get 'contacts', to: 'application#contacts'
  get 'about',    to: 'application#about'

  get 'profile',          to: 'users#profile'
  get 'edit_profile',     to: 'users#edit_profile'
  patch 'update_profile', to: 'users#update_profile'

  post 'comment_like',       to: 'shiny_comments#comment_like'
  post 'comment_dislike',    to: 'shiny_comments#comment_dislike'
  get  'new_sub_comment',    to: 'shiny_comments#new_sub_comment'
  post 'create_sub_comment', to: 'shiny_comments#create_sub_comment'

  resources :shiny_comments
  resources :likes
  

end

app/models/shiny_comment.rb
class ShinyComment < ActiveRecord::Base

	has_many :shiny_comments
	belongs_to :user
	
end

app/controllers/shiny_comments_controller.rb
class ShinyCommentsController < ApplicationController

	def index
    @comment  = ShinyComment.new
    @comments = ShinyComment.where(article_id: params[:article_id])

    @comments = get_second_lvl_comments @comments

    unless current_user.nil?
      @user_comments_id = Like.where(user_id: current_user.id).pluck(:comment_id)
    end

		@article_title = Article.find(params[:article_id]).title
	end

	def create
    @comment = ShinyComment.new(shiny_comment_params)
    @comment[:user_id] = current_user.id


    if @comment.body.blank?
      flash[:notice] = 'Комментарий не может быть пустым'
    else
      @comment.save
      flash[:notice] = 'Ваш комменарий будет опубликован сразу после премодерации'

      article = Article.find(shiny_comment_params[:article_id])
      article.comment_counter += 1
      article.save
    end

    redirect_to :back
	end

  def new_sub_comment # AJAX
    @comment = ShinyComment.new
    @parent_comment_id = params[:parent_comment_id]

    # respond_to do |format|
    #   format.js  
    # end
  end

  def create_sub_comment # AJAX
    @comment = ShinyComment.new(shiny_comment_params)
    @comment[:user_id] = current_user.id
    

    if @comment.body.nil?
      redirect_to :back
    else
      @comment.save

      cmnt = ShinyComment.find(shiny_comment_params[:comment_id])
      article = Article.find(cmnt.article_id)
      article.comment_counter += 1
      article.save

      redirect_to :back
    end

  end


  def comment_like
    if current_user.nil?
      redirect_to :back
    else
      @comment = ShinyComment.find(params[:format])
      @comment.likes += 1
      @comment.save
      @like = Like.create(comment_id: params[:format], user_id: current_user.id)
      redirect_to :back
    end
  end

  def comment_dislike
    if current_user.nil?
      redirect_to :back
    else
      @comment = ShinyComment.find(params[:format])
      @comment.likes -= 1
      @comment.save
      @like = Like.create(comment_id: params[:format], user_id: current_user.id)
      redirect_to :back
    end
  end

  def get_second_lvl_comments arr
    @ids_for_subcomments = arr.pluck(:id)
    @sub_comments = ShinyComment.where(comment_id: @ids_for_subcomments)

    @second_lvl_comments_arr = []

    arr.each do |cmnt|
      sub_cmnts_for_cmnt = @sub_comments.find_all{ |elem| elem.comment_id == cmnt.id } 

      arr_elem = [cmnt, sub_cmnts_for_cmnt]
      @second_lvl_comments_arr << arr_elem

    end

    @second_lvl_comments_arr 
  end

  private

	def shiny_comment_params
    params.require(:shiny_comment).permit(:body, :article_id, :comment_id)
  end

end

app/helpers/shiny_comments_helper.rb
module ShinyCommentsHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/shiny_comments/_comment.html.erb
<div class = 'comment_cont'>
  <div class = 'l_comment_block'>
	  <div class = 'author_pic'>
	  </div>
  </div>
  <div class = 'r_comment_block'>
	  <div class = 'additional_inf'>
	  	<div class = 'nickname'>
	  	  <%= c.user.nick_name %> 
	  	</div>
	  	<div class = 'added_date'>
	  	  <%= c.created_at.strftime('%F') %>  
	  	</div>

	  	<div class = 'likes_cont'>
	  		<% if  current_user.nil?  %>
	  			<div class = 'like_dislike_comment call_popup'>
				  	<span>–</span>
		  		</div>
		  	<% elsif not @user_comments_id.include? c.id %>
		  		<div class = 'like_dislike_comment'>
				  	<%= link_to '–', comment_dislike_path(c.id), method: :post %>
		  		</div>
		  	<% else %>
		 			<div class = 'like_dislike_comment call_popup'>
		  		</div>
	  		<% end %>

	  		<% if c.likes < 0 %>
	  		  <div class = 'negative_likes'>
	  		    <%= c.likes %>
	  		  </div>
	  		<% else %>
	  		  <div class = 'positive_likes'>
	  		    <%= c.likes %>
	  		  </div>
	  		<% end %>

	  		<% if  current_user.nil?  %>
	  			<div class = 'like_dislike_comment call_popup'>
				  	<span>+</span>
		  		</div>
		  	<% elsif not @user_comments_id.include? c.id %>
		  		<div class = 'like_dislike_comment'>
				  	<%= link_to '+', comment_like_path(c.id), method: :post %>
		  		</div>
		  	<% else %>
		 			<div class = 'like_dislike_comment call_popup'>
		  		</div>	
	  		<% end %>
	  	</div>

	  </div>
	  <div class = 'comment_body'>
	  	<%= c.body %>
	  	<!-- временное решение проблему подкомментариев -->
	  	<% if c.comment_id.nil? %> 
	  	  <% if current_user %>
	  		  <span class = 'add_sub_comment_link' data-parent_comment_id = '<%= c.id %>' >Ответить</span>
	  		<% else %>
	  		  <span class = 'for_login_add_sub_comment_link' data-parent_comment_id = '<%= c.id %>' >Ответить</span>
	  	  <% end %>
  	  <% end %>
	  </div>	
  </div>
</div>

app/views/shiny_comments/_new_sub_comment.html.erb
  <div class = 'add_sub_cmnt_cont' id = '<%= @parent_comment_id %>'>
	  <div class = 'sub_comment_close_mark'>
	  </div>	
		<%= form_for @comment, url: create_sub_comment_path do |f| %>
		  <%= f.text_area :body %>
		  <%= f.hidden_field :comment_id, value: @parent_comment_id %>
		  <div class = 'shiny_comments_btn'>
			  <%= f.button :button do %>
			    Ответить
			  <% end %>
		  </div>
		<% end %>
  </div>

app/views/shiny_comments/index.html.erb
<h2><%= @article_title %></h2>

<div class = 'return_link'>
  <%= link_to "К тексту статьи", article_path(params[:article_id]) %>
</div>

<div class = 'parent_comments_cont'>
	<% @comments.each do |c| %>
	  <%= render partial: 'comment', locals: {c: c[0]} %>
	    <div class = 'sub_comment_cont' >
				<% c[1].each do |sub_c| %>
				  <%= render partial: 'comment', locals: {c: sub_c, sub_cmnt_lvl: 2} %>
				<% end %>
	    </div>
	<% end %>

<% if current_user.nil? %>
  <div class = 'comment_add_notice'>
    Для того, чтобы оставить комментарий необходимо <%= link_to 'Авторизоваться', new_user_session_path %>
  </div>
<% else %>
	<div class = 'add_comment_form'>
	  <%= render template: 'shiny_comments/new' %>
	</div>
<% end %>

</div>
<%= render template: 'users/sessions/new_custom' %>

app/views/shiny_comments/new.html.erb
<%= form_for @comment do |f| %>
  <%= f.text_area :body %>
  <%= f.hidden_field :article_id, value: params[:article_id] %>
  <div class = ''>
	  <%= f.button :button do %>
	   Написать комментарий
	  <% end %>
  </div>

<% end %>

app/views/shiny_comments/new_sub_comment.js.erb
arr = $('.add_sub_comment_link');
result = $.grep(arr, function(e){ return e.getAttribute('data-parent_comment_id') == '<%= @parent_comment_id %>'; });

$(result).hide().after("<%= j render(partial: 'new_sub_comment') %>");

$(document).ready(function() {
  $('.sub_comment_close_mark').click(function(){
    $(this).parents('.add_sub_cmnt_cont').hide();
    add_link_id = $(this).parents('.add_sub_cmnt_cont')[0].getAttribute('id') 
    console.log(add_link_id);
    res = $.grep(arr, function(e){ return e.getAttribute('data-parent_comment_id') == add_link_id; });
    $(res).show();
  });
});