config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'articles#blog'

  get 'blog',          to: 'articles#blog'
  get 'basics',        to: 'articles#basics'
  get 'guides',        to: 'articles#guides'
  get '/articles/:id', to: 'articles#show', as: 'article'

  get 'contacts', to: 'application#contacts'
  get 'about',    to: 'application#about'

  get 'profile',          to: 'users#profile'
  get 'edit_profile',     to: 'users#edit_profile'
  patch 'update_profile', to: 'users#update_profile'

  post 'comment_like',       to: 'shiny_comments#comment_like'
  post 'comment_dislike',    to: 'shiny_comments#comment_dislike'
  get  'new_sub_comment',    to: 'shiny_comments#new_sub_comment'
  post 'create_sub_comment', to: 'shiny_comments#create_sub_comment'

  resources :shiny_comments
  resources :likes
  

end

app/models/article.rb
class Article < ActiveRecord::Base

  has_many :shiny_comments
  has_and_belongs_to_many :heros

  has_attached_file :article_pic, styles: { normal: '640x396>' }, default_url: 'dota_default.jpg'
  validates_attachment_content_type :article_pic, content_type: /\Aimage\/.*\Z/
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def blog
		@articles = Article.where(ended: true).page(params[:page]).per(6)
	end

	def basics		
	end

	def guides
	  @guides = Hero.joins("LEFT JOIN articles_heros ON articles_heros.hero_id = heros.id").
	  							 joins("LEFT JOIN articles ON articles.id = articles_heros.article_id").
	  						   where("articles.topic = 'Гайд на героя'").
	  						   order :name   		
	end

	def show
		        @overview = 'Краткий обзор'
		          @skills = 'Механика скиллов'
		       @pick_time = 'Стадия пика'
		          @lining = 'Выбор линии'
		 @hero_bad_choice = 'Неудобные противники'
		@hero_good_choice = 'Удобные противники'
		     @start_items = 'Начальный закуп'
		      @early_game = 'Ранняя стадия'
		        @mid_game = 'Середина игры'
		       @late_game = 'Поздняя стадия'
		  @good_teammates = 'Поговорим о союзниках'
		     @skillbuilds = 'Скиллбилд'

		@article = Article.find(params[:id])
       @hero = Hero.new

		if @article.topic == 'Гайд на героя'
		  article_hero = (ArticlesHero.where article_id: @article.id).first
		  @hero = Hero.find(article_hero.hero_id)
		end


	  if @article.nil?
    	render text: 'Wow... Sorry us, but page not found', status: 404
    else
      add_view
    end
	end

	def add_view
		@article = Article.find(params[:id])

		view = View.new
		view.article_id = params[:id]
		view.client_ip = request.remote_ip

		if current_user
		  view.user_id = current_user.id
		  if (View.find_by user_id: current_user.id).nil?
		  	@article.view_counter += 1
		  	@article.save
		    view.save 
		  end 
		else		  
		  if (View.find_by client_ip: request.remote_ip).nil?
		  	@article.view_counter += 1
		  	@article.save
		    view.save 
		  end
		end
	end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/basics.html.erb
Статьи с темой "Основы"

app/views/articles/blog.html.erb
<div>
	<% @articles.each do |a| %>
		<%= link_to article_path(a.id) do %>
			<div class = 'article_block'>
				<div class = 'article_pic'>
				  <%= image_tag a.article_pic.url(:normal) %>
				</div>
				<div class = 'article_title'>
				  <%= a.title %>
				</div>
				<div class = 'article_preview'>
					  <%= a.preview %>
					<div class = 'comment_and_view_pic'>
						<%= image_tag 'comment.png' %>
				    <%= a.comment_counter %>
					</div>
				  <div class = 'comment_and_view_pic'>
						<%= image_tag 'view.png' %>	
					  <%= a.view_counter %>
					</div>
				</div>
			</div>
		<% end %>
	<% end %>
</div>

<div class = 'paginate_cont'>
  <%= paginate @articles, :window => 2 %>
</div>

app/views/articles/guides.html.erb
<div class = 'guides_cont'>

	<% main_letter = 'A' %>
  <div class ='main_letter'>
      <%= main_letter %>
  </div>

	<% @guides.each_with_index do |g, ind| %>
	    <% if g.name[0] != main_letter %>
	      <%  main_letter = g.name[0] %>
			  <div class ='main_letter'>
			    <%= main_letter %>
			  </div>
	    <% end %>

		<div class = 'guide_elem'>
			<%= link_to article_path(g.articles[0].id) do %>
			  <%= image_tag g.hero_pic.url(:normal) %>
				<div class = 'guide_hero_name'>
				  <%= g.name %>
				</div>
			<% end %>
		</div>

	<% end %>
</div>

app/views/articles/show.html.erb
<% content_for :article_content_list do %>
	<div class = 'left_side_cont'>
		<div id = 'parent_content_list'>
			<div class = 'content_list'>

				<b>Содержание</b>

				<div class = 'content_list_elem dark_content_link'>
				  <a href = '#begin'>К началу</a>
				</div>

				<div class = 'content_list_elem'>
				  <a href = '#overview'>Краткий обзор</a>
			  </div>
				
				<div class = 'content_list_elem dark_content_link'>
				  <a href = '#skills'>Механика скиллов</a>
				</div>

				<div class = 'content_list_elem'>
				  <a href = '#pick_time'>Стадия пика</a>
				</div>  
				
				<div class = 'content_list_elem dark_content_link'>
		      <a href = '#lining'>Выбор линии</a>
				</div>

				<div class = 'content_list_elem'>
				  <a href = '#hero_bad_choice'>Неудобные противники</a>
				</div>

				<div class = 'content_list_elem dark_content_link'>
				  <a href = '#hero_good_choice'>Удобные противники</a>
				</div>

				<div class = 'content_list_elem'>
				  <a href = '#start_items'>Начальный закуп</a>
				</div>

				<div class = 'content_list_elem dark_content_link'>	
				  <a href = '#early_game'>Ранняя стадия</a>
				</div>

				<div class = 'content_list_elem'>
				  <a href = '#mid_game'>Середина игры</a>
				</div>

				<div class = 'content_list_elem dark_content_link'>
				  <a href = '#late_game'>Поздняя стадия</a>
				</div>

				<div class = 'content_list_elem'>
				  <a href = '#good_teammates'>Поговорим о союзниках</a>
				</div>

				<div class = 'content_list_elem dark_content_link'>		
				 <a href = '#skillbuilds'>Скиллбилд</a>
				</div>

			</div>

			<div class = 'hide_content_list'>
				<div class = 'hide_triangle'></div>
				Спрятать
			</div>

			<div class = 'show_content_list'>
				Показать
				<div class = 'show_triangle'></div>
			</div>
		</div>
	</div>
<% end %>

<div class = 'article_cont'>

	<a id = 'begin' ></a>

	<h2><%= @article.title %></h2>

  <div class = 'hero_inf_cont'>
	  <div class = 'article_pic_on_show_page'>
		  <%= image_tag @article.article_pic.url(:normal) %>
	  </div>
	  <div class = 'hero_roles'>
	  	<% @hero.roles.each_with_index do |r,i| %>
	  	  <%= r %>
	  	  <% if i != @hero.roles.size - 1 and i != 0 %>
	  	  ,
	  	  <% end %>
	  	<% end %>
	  </div>
  </div>

  <div class = 'hero_inf_cont'>
	  <div class = 'base_attr_cont'>
	  	<div class = 'base_attr_elem'>
	  	  <%= image_tag 'str.png' %>
	  	</div>
	  	<div class = 'base_attr_elem_value'>
	  		<%= "%g" % @hero.base_strength %> + <%= @hero.increase_strength %>
	  	</div>
	  	<div class = 'base_attr_elem'>
	  	  <%= image_tag 'agl.png' %>
	  	</div>
	  	<div class = 'base_attr_elem_value'>
	  		<%= "%g" % @hero.base_agility %> + <%= @hero.increase_agility %>
	  	</div>
	  	<div class = 'base_attr_elem'>
	  	  <%= image_tag 'int.png' %>
	  	</div>
	  	<div class = 'base_attr_elem_value'>
	  		<%= "%g" % @hero.base_intelligence %> + <%= @hero.increase_intelligence%>
	  	</div>
	  </div>

	  <div class = 'hero_attr_cont_with_name'>
	  	<div class = 'hero_attr_elem'>
	  		Скорость передвижения: 
	  	</div>
	    <div class = 'hero_attr_elem'>
	  	  Базовый армор: 
	    </div>
	    <div class = 'hero_attr_elem'>
	  	  Урон: 
	    </div>
	    <div class = 'hero_attr_elem'>
	  	  Дальность атаки: 
	    </div>
	    <div class = 'hero_attr_elem'>
	  	  Базовая скорость атаки: 
	    </div>
	    <div class = 'hero_attr_elem'>
	  	  Скорость поворота: 
	    </div>
	    <div class = 'hero_attr_elem'>
	  	  Базовая регенерация HP: 
	    </div>
	  </div>

	  <div class = 'hero_attr_cont_with_value'>
	  	<div class = 'hero_attr_elem'>
	  		<%= "%g" % @hero.base_movement_speed %>
	  	</div>
	    <div class = 'hero_attr_elem'>
	    	<%= "%g" % @hero.base_armor %>
	    </div>
	    <div class = 'hero_attr_elem'>
	  	  <%= "%g" % @hero.base_min_damage %> - <%= "%g" % @hero.base_max_damage %>
	    </div>
	    <div class = 'hero_attr_elem'>
	  	  <%= "%g" % @hero.attack_range %>
	    </div>
	    <div class = 'hero_attr_elem'>
	  	  <%= @hero.base_attack_time %>
	    </div>
	    <div class = 'hero_attr_elem'>
	  	  <%= @hero.rotation_speed %>
	    </div>
	    <div class = 'hero_attr_elem'>
	  	  <%= @hero.base_hp_regen %>
	    </div>
	  </div>
  </div>

	<%= raw ERB.new(@article.body).result(binding) %>
</div>

<div class = 'article_additional_info'>
	<%= link_to "Посмотреть комментарии (#{@article.comment_counter})", shiny_comments_path(article_id: @article.id) %>
	<div class = 'article_inf_elem'>
	  Просмотров: <%= @article.view_counter %>
	</div>
	<div class = 'article_inf_elem'>
	  Обновлён: <%= @article.updated_at.strftime('%F') %>
	</div>
</div>