config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'articles#blog'

  get 'blog',          to: 'articles#blog'
  get 'basics',        to: 'articles#basics'
  get 'guides',        to: 'articles#guides'
  get '/articles/:id', to: 'articles#show', as: 'article'

  get 'contacts', to: 'application#contacts'
  get 'about',    to: 'application#about'

  get 'profile',          to: 'users#profile'
  get 'edit_profile',     to: 'users#edit_profile'
  patch 'update_profile', to: 'users#update_profile'

  post 'comment_like',       to: 'shiny_comments#comment_like'
  post 'comment_dislike',    to: 'shiny_comments#comment_dislike'
  get  'new_sub_comment',    to: 'shiny_comments#new_sub_comment'
  post 'create_sub_comment', to: 'shiny_comments#create_sub_comment'

  resources :shiny_comments
  resources :likes
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shiny</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class = 'top_cont'>
  </div>

  <div class = 'menu_cont'>
  	<%= link_to blog_path do %>
  	  <div class = 'menu_cont_elem'>
  	    Блог
  	  </div>
  	<% end %>
  	<%= link_to basics_path do %>
  	  <div class = 'menu_cont_elem'>
  	    Основы
  	  </div>
  	<% end %>
  	<%= link_to guides_path do %>
  	  <div class = 'menu_cont_elem'>
  	    Гайды
  	  </div>
  	<% end %>
  </div>

  <div class = 'mid_cont'>

    <%= yield :article_content_list %>

  	<div class = 'content_cont'>
	    <%= yield %>
  	</div>

  	<div class = 'right_side_cont'>
      <div class = 'parent_login_cont'>
        <div class = 'login_cont'>
          <%= link_to 'Войти', new_user_session_path  %>
          <%= link_to 'Зарегистрироваться', new_user_registration_path  %>
        </div>
      </div> 
      <div class = 'right_banner'></div>
  	</div>
  </div>

  <div class = 'bot_cont'>
    <%= link_to 'О проекте', about_path %>
    <%= link_to 'Контакты', contacts_path %>    
  </div>

</body>
</html>